# Extra autostart processes
# exec-once = uwsm app -- my-service

# # Start wob for volume (screen 0)
# exec-once = sh -c "cat ~/.config/wob/volume | wob -s 0 -h 5 -c 0xffff0000 &"
# # Start wob for brightness (screen 0)
# exec-once = sh -c "cat ~/.config/wob/brightness | wob -s 0 -h 5 -c 0xff00ff00 &"
#
#


exec-once = bash -c 'socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | grep --line-buffered "openwindow" | while read line; do class=$(echo "$line" | cut -d"," -f3); if [ "$class" = "org.gnome.Nautilus" ] || [ "$class" = "org.omarchy.impala" ]; then active=$(hyprctl activeworkspace -j | python3 -c "import sys,json; print(json.load(sys.stdin)[\"id\"])"); hyprctl dispatch movetoworkspace "$active,class:^($class)$"; fi; done'
