# Source Omarchy application bindings
# bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new

source = ~/.local/share/omarchy/config/hypr/bindings.conf

bind = SUPER SHIFT, I, exec, flatpak run com.brave.Browser

