# Source Omarchy application bindings
# bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new

source = ~/.local/share/omarchy/config/hypr/bindings.conf

bind = SUPER SHIFT, I, exec, flatpak run com.brave.Browser
bind = SUPER SHIFT, K, exec, xdg-open ~/Documents/Computer\ Systems\ A\ Programmers\ Perspective\ 2nd\ Edition---Randal\ Bryant\ David\ Hallaron.pdf

bind = SUPER SHIFT, U, exec, /home/traveller/aseprite/aseprite-release/bin/aseprite

